# Generated by Django 5.1.2 on 2024-10-09 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_details"),
    ]

    operations = [
        migrations.DeleteModel(
            name="details",
        ),
    ]
