# Generated by Django 5.1.2 on 2024-10-09 05:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_delete_user_details"),
    ]

    operations = [
        migrations.CreateModel(
            name="user_contact_details",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address", models.TextField(max_length=100)),
                ("city", models.CharField(max_length=50)),
                ("zipcode", models.CharField(max_length=6)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.user"
                    ),
                ),
            ],
        ),
    ]
